version: "3"
services:
  rabbitdocker:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitdocker'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

